name: icon-theme-pocillo
build-base: core24
base: bare
version: '0.22.1'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Pocillo icon theme for Snaps
description: |
  A snap that exports the Pocillo icon theme.
grade: stable
confinement: strict
compression: lzo

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Pocillo
        - $SNAP/share/icons/Pocillo-light
        - $SNAP/share/icons/TelaBudgie
        - $SNAP/share/icons/TelaBudgie-dark
        - $SNAP/share/icons/TelaBudgie-light
parts:
  pocillo-icon-theme:
    plugin: dump
    source: http://de.archive.ubuntu.com/ubuntu/pool/universe/b/budgie-artwork/pocillo-icon-theme_$SNAPCRAFT_PROJECT_VERSION_all.deb
    organize:
      usr/share/icons: share/icons
    prime:
      - share/icons/
