name: icon-theme-pocillo
build-base: core24
base: bare
version: '0.21.1'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Pocillo icon theme for Snaps
description: |
  A snap that exports the Pocillo icon theme.
grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Pocillo
        - $SNAP/share/icons/Pocillo-light
        - $SNAP/share/icons/TelaBudgie
        - $SNAP/share/icons/TelaBudgie-dark
        - $SNAP/share/icons/TelaBudgie-light
parts:
  pocillo-icon-themes:
    plugin: dump
    source: http://de.archive.ubuntu.com/ubuntu/pool/universe/b/budgie-artwork/pocillo-icon-theme_0.21.1_all.deb
    override-build: |
      snapcraftctl build
      pwd
      ls -l
      mkdir -p $CRAFT_PART_INSTALL/share/icons
      mv -f $CRAFT_PART_INSTALL/usr/share/icons/* $CRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/
